version: "4.1"
services:
    nopcommerce_web:
        build: .
        container_name: hsdev_web
        ports:
            - "80:80"
        depends_on:
            - hsdev_database
    nopcommerce_database:
        image: "microsoft/mssql-server-linux"
        container_name: nopcommerce_mssql_server
        environment:
            SA_PASSWORD: "265%Power"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"

volumes:
  nopcommerce_data: "/c/nop-server"